global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["65.2.179.208:9100"]  # Alertmanager (optional)

rule_files:
  - "alert.rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node"
    static_configs:
      - targets: ["localhost:9100"]           # Node Exporter on Master     
      - targets: ["65.2.179.208:9100"]     # Node Exporter on Web Server

  - job_name: "blackbox"
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - https://github.com/NikGaykwad/Capstone-Project-Nik
          - http://65.2.179.208:8080/
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9115  # IP/hostname of Blackbox Exporter (your Master Server)

